import { Penerima } from '@/contexts/PenerimaContext';

export const initialPenerimaData: Omit<Penerima, 'id' | 'sudahMenerima'>[] = [
  // RT 01 - Data dari gambar (180 orang total, nomor 1-180)
  { nomorPengambilan: '1', nama: 'HERMAN (Mondok di Kos Islamah)', rt: '01', blok: 'Barat' },
  { nomorPengambilan: '2', nama: 'SUYATNO', rt: '01', blok: 'Barat' },
  { nomorPengambilan: '3', nama: 'SUKIR', rt: '01', blok: 'Barat' },
  { nomorPengambilan: '4', nama: 'RAHAYU ISHARYANTO W', rt: '01', blok: 'Barat' },
  { nomorPengambilan: '5', nama: 'SUYATMI', rt: '01', blok: 'Barat' },
  { nomorPengambilan: '6', nama: 'JUMINGAN', rt: '01', blok: 'Barat' },
  { nomorPengambilan: '7', nama: 'PARWI', rt: '01', blok: 'Barat' },
  { nomorPengambilan: '8', nama: 'SARTO', rt: '01', blok: 'Barat' },
  { nomorPengambilan: '9', nama: 'SARNGADI', rt: '01', blok: 'Barat' },
  { nomorPengambilan: '10', nama: 'SUTARTO', rt: '01', blok: 'Barat' },
  { nomorPengambilan: '11', nama: 'DARMO TAMBIR', rt: '01', blok: 'Barat' },
  { nomorPengambilan: '12', nama: 'FAJAR (Mondok B. Parjan)', rt: '01', blok: 'Barat' },
  { nomorPengambilan: '13', nama: 'TIKA (Mondok Bp. Parjan)', rt: '01', blok: 'Barat' },
  { nomorPengambilan: '14', nama: 'PASMANTO', rt: '01', blok: 'Barat' },
  { nomorPengambilan: '15', nama: 'BODET I', rt: '01', blok: 'Barat' },
  { nomorPengambilan: '16', nama: 'TRIYATNO', rt: '01', blok: 'Barat' },
  { nomorPengambilan: '17', nama: 'H. SUPARNO', rt: '01', blok: 'Barat' },
  { nomorPengambilan: '18', nama: 'SUWARDI / TRISNO', rt: '01', blok: 'Barat' },
  { nomorPengambilan: '19', nama: 'DEDIK', rt: '01', blok: 'Barat' },
  { nomorPengambilan: '20', nama: 'AGUS SETIYONO', rt: '01', blok: 'Barat' },
  { nomorPengambilan: '21', nama: 'KASIMAN', rt: '01', blok: 'Barat' },
  { nomorPengambilan: '22', nama: 'WARNI', rt: '01', blok: 'Barat' },
  { nomorPengambilan: '23', nama: 'SUTIMIN', rt: '01', blok: 'Barat' },
  { nomorPengambilan: '24', nama: 'DWI AGUS SARYANTO', rt: '01', blok: 'Barat' },
  { nomorPengambilan: '25', nama: 'MARDI UTOMO, SH', rt: '01', blok: 'Barat' },
  { nomorPengambilan: '26', nama: 'SUDARSO, SH', rt: '01', blok: 'Barat' },
  { nomorPengambilan: '27', nama: 'ERLAN', rt: '01', blok: 'Barat' },
  { nomorPengambilan: '28', nama: 'TONO SUCIPTO', rt: '01', blok: 'Barat' },
  { nomorPengambilan: '29', nama: 'EDI PRAWOTO', rt: '01', blok: 'Barat' },
  { nomorPengambilan: '30', nama: 'RURI', rt: '01', blok: 'Barat' },
  { nomorPengambilan: '31', nama: 'PARJAN', rt: '01', blok: 'Barat' },
  { nomorPengambilan: '32', nama: 'TUKIMIN', rt: '01', blok: 'Barat' },
  { nomorPengambilan: '33', nama: 'SUPRIYANTA', rt: '01', blok: 'Barat' },
  { nomorPengambilan: '34', nama: 'YUSUF CAHYO PUTRO', rt: '01', blok: 'Barat' },
  { nomorPengambilan: '35', nama: 'SUTINO', rt: '01', blok: 'Barat' },
  { nomorPengambilan: '36', nama: 'TINI', rt: '01', blok: 'Barat' },
  { nomorPengambilan: '37', nama: 'SUKRI KLAMBONO', rt: '01', blok: 'Barat' },
  { nomorPengambilan: '38', nama: 'PUTHUT RULLY K, SH., MH', rt: '01', blok: 'Barat' },
  { nomorPengambilan: '39', nama: 'YULI/ERNA', rt: '01', blok: 'Barat' },
  { nomorPengambilan: '40', nama: 'WULAN (NANO)', rt: '01', blok: 'Barat' },
  { nomorPengambilan: '41', nama: 'WIDODO TERMINAL', rt: '01', blok: 'Barat' },
  { nomorPengambilan: '42', nama: 'INDARTI', rt: '01', blok: 'Barat' },
  { nomorPengambilan: '43', nama: 'BODET 2', rt: '01', blok: 'Barat' },
  { nomorPengambilan: '44', nama: 'SUYADI/RUS', rt: '01', blok: 'Barat' },
  { nomorPengambilan: '45', nama: 'SUPALI', rt: '01', blok: 'Barat' },
  { nomorPengambilan: '46', nama: 'MANTO', rt: '01', blok: 'Barat' },
  { nomorPengambilan: '47', nama: 'AWAN B', rt: '01', blok: 'Barat' },
  { nomorPengambilan: '48', nama: 'SARYATI', rt: '01', blok: 'Barat' },
  { nomorPengambilan: '49', nama: 'DAYA', rt: '01', blok: 'Barat' },
  { nomorPengambilan: '50', nama: 'WARI / NUNUNG (Tower)', rt: '01', blok: 'Barat' },
  { nomorPengambilan: '51', nama: 'BUDI (PERUM RESIDENCE)', rt: '01', blok: 'Barat' },
  { nomorPengambilan: '52', nama: 'ENDAR MEGA (PERUM RESIDENCE)', rt: '01', blok: 'Barat' },
  { nomorPengambilan: '53', nama: 'AMIR SUKARDI (PERUM RESIDENCE)', rt: '01', blok: 'Barat' },
  { nomorPengambilan: '54', nama: 'RAMLAN (PERUM RESIDENCE)', rt: '01', blok: 'Barat' },
  { nomorPengambilan: '55', nama: 'USTAD SYUKUR', rt: '01', blok: 'Barat' },
  { nomorPengambilan: '56', nama: 'Beli Sapi PARJAN', rt: '01', blok: 'Barat' },
  { nomorPengambilan: '57', nama: 'KETUA RW (RURI)', rt: '01', blok: 'Barat' },
  { nomorPengambilan: '58', nama: 'GIYANTO/GEMI', rt: '01', blok: 'Barat' },
  { nomorPengambilan: '59', nama: 'DESI', rt: '01', blok: 'Barat' },
  { nomorPengambilan: '60', nama: 'BAWAH TOWER 1', rt: '01', blok: 'Barat' },
  { nomorPengambilan: '61', nama: 'BAWAH TOWER 2', rt: '01', blok: 'Barat' },
  { nomorPengambilan: '62', nama: 'BAWAH TOWER 3', rt: '01', blok: 'Barat' },
  { nomorPengambilan: '63', nama: 'Gudang Pajo', rt: '01', blok: 'Barat' },
  { nomorPengambilan: '64', nama: 'Salamah', rt: '01', blok: 'Barat' },
  { nomorPengambilan: '65', nama: 'Tono Cipto', rt: '01', blok: 'Barat' },
  { nomorPengambilan: '66', nama: 'Arli / Glento', rt: '01', blok: 'Barat' },
  { nomorPengambilan: '67', nama: 'Epa Purwantoko Rini Palupi (Belakang Tresno)', rt: '01', blok: 'Barat' },
  { nomorPengambilan: '68', nama: 'PAK RT (PARJAN)', rt: '01', blok: 'Barat' },
  { nomorPengambilan: '69', nama: 'AGUNG RIADI (Mondok Bp. Kasiman)', rt: '01', blok: 'Barat' },
  { nomorPengambilan: '70', nama: 'FAJAR (Depan BP. Agus Setiyono)', rt: '01', blok: 'Barat' },
  { nomorPengambilan: '71', nama: 'ANDANG (Mondok depan BP. Agus Setiyono)', rt: '01', blok: 'Barat' },
  { nomorPengambilan: '72', nama: 'GIYONO/KASMI', rt: '01', blok: 'Tengah' },
  { nomorPengambilan: '73', nama: 'GIGIH MOTOR', rt: '01', blok: 'Tengah' },
  { nomorPengambilan: '74', nama: 'ABDUL ROHMAN', rt: '01', blok: 'Tengah' },
  { nomorPengambilan: '75', nama: 'WARSITO', rt: '01', blok: 'Tengah' },
  { nomorPengambilan: '76', nama: 'KHUSNUL', rt: '01', blok: 'Tengah' },
  { nomorPengambilan: '77', nama: 'DONA / IWAN', rt: '01', blok: 'Tengah' },
  { nomorPengambilan: '78', nama: 'NUNUNG KUNCORO', rt: '01', blok: 'Tengah' },
  { nomorPengambilan: '79', nama: 'HANI P', rt: '01', blok: 'Tengah' },
  { nomorPengambilan: '80', nama: 'JUMADI/LIA', rt: '01', blok: 'Tengah' },
  { nomorPengambilan: '81', nama: 'WARDOYO', rt: '01', blok: 'Tengah' },
  { nomorPengambilan: '82', nama: 'H. SUBADI', rt: '01', blok: 'Tengah' },
  { nomorPengambilan: '83', nama: 'NIKA', rt: '01', blok: 'Tengah' },
  { nomorPengambilan: '84', nama: 'TORO / ITA', rt: '01', blok: 'Tengah' },
  { nomorPengambilan: '85', nama: 'UDI SANTOSO', rt: '01', blok: 'Tengah' },
  { nomorPengambilan: '86', nama: 'ANDI BAROTO PURWO', rt: '01', blok: 'Tengah' },
  { nomorPengambilan: '87', nama: 'DARMO', rt: '01', blok: 'Tengah' },
  { nomorPengambilan: '88', nama: 'DITA PAMBUDI (Depan Mas Tarmo)', rt: '01', blok: 'Tengah' },
  { nomorPengambilan: '89', nama: 'SAMBA', rt: '01', blok: 'Tengah' },
  { nomorPengambilan: '90', nama: 'KRISTANTO SOFYAN', rt: '01', blok: 'Tengah' },
  { nomorPengambilan: '91', nama: 'TUKINO', rt: '01', blok: 'Tengah' },
  { nomorPengambilan: '92', nama: 'WIJIATMI', rt: '01', blok: 'Tengah' },
  { nomorPengambilan: '93', nama: 'SUGIYONO', rt: '01', blok: 'Tengah' },
  { nomorPengambilan: '94', nama: 'NGATIMIN', rt: '01', blok: 'Tengah' },
  { nomorPengambilan: '95', nama: 'SUKINO', rt: '01', blok: 'Tengah' },
  
  // Melanjutkan RT 01 nomor 96-180 dari gambar kedua
  { nomorPengambilan: '96', nama: 'SRI SUWASMI (IG. SUGIYARTO)', rt: '01', blok: 'Tengah' },
  { nomorPengambilan: '97', nama: 'DWI ENI S / WIWIK', rt: '01', blok: 'Tengah' },
  { nomorPengambilan: '98', nama: 'SUNARDI', rt: '01', blok: 'Tengah' },
  { nomorPengambilan: '99', nama: 'TUKIMAN', rt: '01', blok: 'Tengah' },
  { nomorPengambilan: '100', nama: 'CHOIRUL AMIM', rt: '01', blok: 'Tengah' },
  { nomorPengambilan: '101', nama: 'MARMI (ALM. WARMIN)', rt: '01', blok: 'Tengah' },
  { nomorPengambilan: '102', nama: 'KASIKEM', rt: '01', blok: 'Tengah' },
  { nomorPengambilan: '103', nama: 'MULYANI', rt: '01', blok: 'Tengah' },
  { nomorPengambilan: '104', nama: 'ENDRIAS / SABAR', rt: '01', blok: 'Tengah' },
  { nomorPengambilan: '105', nama: 'ASRUN', rt: '01', blok: 'Tengah' },
  { nomorPengambilan: '106', nama: 'AGUS SUSANTO', rt: '01', blok: 'Tengah' },
  { nomorPengambilan: '107', nama: 'WARIJO (BAGONG)', rt: '01', blok: 'Tengah' },
  { nomorPengambilan: '108', nama: 'SRI HARTONO, S.Pd', rt: '01', blok: 'Tengah' },
  { nomorPengambilan: '109', nama: 'JATMIKO (SAMIYONO)', rt: '01', blok: 'Tengah' },
  { nomorPengambilan: '110', nama: 'WARDI/DANANG', rt: '01', blok: 'Tengah' },
  { nomorPengambilan: '111', nama: 'MARYATMO', rt: '01', blok: 'Tengah' },
  { nomorPengambilan: '112', nama: 'CIPTO WIYADI', rt: '01', blok: 'Tengah' },
  { nomorPengambilan: '113', nama: 'H. DAROJI', rt: '01', blok: 'Tengah' },
  { nomorPengambilan: '114', nama: 'DANANG HARIYANTO, S.Pd', rt: '01', blok: 'Tengah' },
  { nomorPengambilan: '115', nama: 'SURONO', rt: '01', blok: 'Tengah' },
  { nomorPengambilan: '116', nama: 'SUKATNO', rt: '01', blok: 'Tengah' },
  { nomorPengambilan: '117', nama: 'SUGENG MURJIANTO', rt: '01', blok: 'Tengah' },
  { nomorPengambilan: '118', nama: 'SARMIN, S.Pd', rt: '01', blok: 'Tengah' },
  { nomorPengambilan: '119', nama: 'TARMO', rt: '01', blok: 'Tengah' },
  { nomorPengambilan: '120', nama: 'SUGIYANTO', rt: '01', blok: 'Tengah' },
  { nomorPengambilan: '121', nama: 'IBU JOKO SARTONO', rt: '01', blok: 'Tengah' },
  { nomorPengambilan: '122', nama: 'MUHADI', rt: '01', blok: 'Tengah' },
  { nomorPengambilan: '123', nama: 'Harun Suparman', rt: '01', blok: 'Tengah' },
  { nomorPengambilan: '124', nama: 'Lintas Tama', rt: '01', blok: 'Tengah' },
  { nomorPengambilan: '125', nama: 'RIWUK (Rumah Alm. Bp. Mamo Nasgor)', rt: '01', blok: 'Tengah' },
  { nomorPengambilan: '126', nama: 'MAGENDI (Mondok Bp. Toni)', rt: '01', blok: 'Tengah' },
  { nomorPengambilan: '127', nama: 'SRI PINILIH', rt: '01', blok: 'Tengah' },
  { nomorPengambilan: '128', nama: 'Mondok Rumah Bibik', rt: '01', blok: 'Tengah' },
  { nomorPengambilan: '129', nama: 'Barat Pak Fatkurohman', rt: '01', blok: 'Tengah' },
  { nomorPengambilan: '130', nama: 'TUGIMIN ADHI WIYONO', rt: '01', blok: 'Timur' },
  { nomorPengambilan: '131', nama: 'FATKURROHMAN', rt: '01', blok: 'Timur' },
  { nomorPengambilan: '132', nama: 'H. MARYANTO', rt: '01', blok: 'Timur' },
  { nomorPengambilan: '133', nama: 'TUKIRAN', rt: '01', blok: 'Timur' },
  { nomorPengambilan: '134', nama: 'H. HILMAN SUYATMAN', rt: '01', blok: 'Timur' },
  { nomorPengambilan: '135', nama: 'UMAR SUKAMTO', rt: '01', blok: 'Timur' },
  { nomorPengambilan: '136', nama: 'SUWITO', rt: '01', blok: 'Timur' },
  { nomorPengambilan: '137', nama: 'ARIS SETIYONO', rt: '01', blok: 'Timur' },
  { nomorPengambilan: '138', nama: 'SUYANTO (NDOT)', rt: '01', blok: 'Timur' },
  { nomorPengambilan: '139', nama: 'SUYATI', rt: '01', blok: 'Timur' },
  { nomorPengambilan: '140', nama: 'SUNARMI', rt: '01', blok: 'Timur' },
  { nomorPengambilan: '141', nama: 'SRIYATNO', rt: '01', blok: 'Timur' },
  { nomorPengambilan: '142', nama: 'SUTANTO', rt: '01', blok: 'Timur' },
  { nomorPengambilan: '143', nama: 'H. GINO (ISTIQOMAH)', rt: '01', blok: 'Timur' },
  { nomorPengambilan: '144', nama: 'JUMAR', rt: '01', blok: 'Timur' },
  { nomorPengambilan: '145', nama: 'SLAMET', rt: '01', blok: 'Timur' },
  { nomorPengambilan: '146', nama: 'BAMBANG PURBIANTORO', rt: '01', blok: 'Timur' },
  { nomorPengambilan: '147', nama: 'BAMBANG SUWONDO', rt: '01', blok: 'Timur' },
  { nomorPengambilan: '148', nama: 'SURYANTO', rt: '01', blok: 'Timur' },
  { nomorPengambilan: '149', nama: 'TIMIN', rt: '01', blok: 'Timur' },
  { nomorPengambilan: '150', nama: 'PARJO', rt: '01', blok: 'Timur' },
  { nomorPengambilan: '151', nama: 'KARDI', rt: '01', blok: 'Timur' },
  { nomorPengambilan: '152', nama: 'TRI ISMO', rt: '01', blok: 'Timur' },
  { nomorPengambilan: '153', nama: 'JUMADI (Nemon)', rt: '01', blok: 'Timur' },
  { nomorPengambilan: '154', nama: 'PIPIN', rt: '01', blok: 'Timur' },
  { nomorPengambilan: '155', nama: 'EKO SAPUTRO', rt: '01', blok: 'Timur' },
  { nomorPengambilan: '156', nama: 'SONI WN', rt: '01', blok: 'Timur' },
  { nomorPengambilan: '157', nama: 'HARYADI/IRA', rt: '01', blok: 'Timur' },
  { nomorPengambilan: '158', nama: 'H. SRI KARTINI (SULATMIN)', rt: '01', blok: 'Timur' },
  { nomorPengambilan: '159', nama: 'JUM (Bp. Yatman)', rt: '01', blok: 'Timur' },
  { nomorPengambilan: '160', nama: 'Khotib Jumat (Bp. H. Sumarjo)', rt: '01', blok: 'Timur' },
  { nomorPengambilan: '161', nama: 'ARIP (Bp. Yatman)', rt: '01', blok: 'Timur' },
  { nomorPengambilan: '162', nama: 'Beli Sapi SUYATMAN', rt: '01', blok: 'Timur' },
  { nomorPengambilan: '163', nama: 'TAKMIR MASJID (H. HILMAN SUYATMAN)', rt: '01', blok: 'Timur' },
  { nomorPengambilan: '164', nama: 'ISTIQOMAH (Pengasuh)', rt: '01', blok: 'Timur' },
  { nomorPengambilan: '165', nama: 'UST. DIKA', rt: '01', blok: 'Timur' },
  { nomorPengambilan: '166', nama: 'KHOTIB JUMAT 1 (H. Hilman Suyatman)', rt: '01', blok: 'Timur' },
  { nomorPengambilan: '167', nama: 'KHOTIB JUMAT 3 (Ust. Syukur)', rt: '01', blok: 'Timur' },
  { nomorPengambilan: '168', nama: 'KHOTIB JUMAT 4 (Topo Broto)', rt: '01', blok: 'Timur' },
  { nomorPengambilan: '169', nama: 'NANANG (MASJID)', rt: '01', blok: 'Timur' },
  { nomorPengambilan: '170', nama: 'KETUA PENGASUH PENGAJIAN', rt: '01', blok: 'Timur' },
  { nomorPengambilan: '171', nama: 'PENGASUH PENGAJIAN', rt: '01', blok: 'Timur' },
  { nomorPengambilan: '172', nama: 'Perumahan Ringin Agung 1 (Joko Santoso)', rt: '01', blok: 'Timur' },
  { nomorPengambilan: '173', nama: 'Perumahan Ringin Agung 2', rt: '01', blok: 'Timur' },
  { nomorPengambilan: '174', nama: 'Perumahan Ringin Agung 3 (Koperasi)', rt: '01', blok: 'Timur' },
  { nomorPengambilan: '175', nama: 'Perumahan Ringin Agung 4', rt: '01', blok: 'Timur' },
  { nomorPengambilan: '176', nama: 'H. Hilman Suyatman (Pengasuh 1)', rt: '01', blok: 'Timur' },
  { nomorPengambilan: '177', nama: 'Ust Syukur (Pengasuh 2)', rt: '01', blok: 'Timur' },
  { nomorPengambilan: '178', nama: 'Ust. Gimin (Pengasuh 3)', rt: '01', blok: 'Timur' },
  { nomorPengambilan: '179', nama: 'Ana / Ani', rt: '01', blok: 'Timur' },
  { nomorPengambilan: '180', nama: 'Ust. Muafiq', rt: '01', blok: 'Timur' },

  // RT 02 - Data dari gambar (155 orang total, nomor 1-155)
  { nomorPengambilan: '1', nama: 'AGUNG KURNIANTO', rt: '02', blok: 'Barat I' },
  { nomorPengambilan: '2', nama: 'DEWI (WARI)', rt: '02', blok: 'Barat I' },
  { nomorPengambilan: '3', nama: 'DEWI SUTARTI', rt: '02', blok: 'Barat I' },
  { nomorPengambilan: '4', nama: 'SHOLEH', rt: '02', blok: 'Barat I' },
  { nomorPengambilan: '5', nama: 'SUBUR', rt: '02', blok: 'Barat I' },
  { nomorPengambilan: '6', nama: 'SUPARJO', rt: '02', blok: 'Barat I' },
  { nomorPengambilan: '7', nama: 'HARI LIS', rt: '02', blok: 'Barat I' },
  { nomorPengambilan: '8', nama: 'RIZAL', rt: '02', blok: 'Barat I' },
  { nomorPengambilan: '9', nama: 'ARI SURYAWAN', rt: '02', blok: 'Barat I' },
  { nomorPengambilan: '10', nama: 'SATIMIN', rt: '02', blok: 'Barat I' },
  { nomorPengambilan: '11', nama: 'WIDODO SURIP', rt: '02', blok: 'Barat I' },
  { nomorPengambilan: '12', nama: 'SRI WURYANI JANGKUNG', rt: '02', blok: 'Barat I' },
  { nomorPengambilan: '13', nama: 'SUPRIYONO CV', rt: '02', blok: 'Barat I' },
  { nomorPengambilan: '14', nama: 'SUKIYATNO', rt: '02', blok: 'Barat I' },
  { nomorPengambilan: '15', nama: 'SUMADI GENDUT', rt: '02', blok: 'Barat I' },
  { nomorPengambilan: '16', nama: 'AGUS SUNARJO', rt: '02', blok: 'Barat I' },
  { nomorPengambilan: '17', nama: 'WARNI / TUMIYEM / ALM SUKATMO', rt: '02', blok: 'Barat I' },
  { nomorPengambilan: '18', nama: 'KASINO', rt: '02', blok: 'Barat I' },
  { nomorPengambilan: '19', nama: 'MENTO WIYONO', rt: '02', blok: 'Barat I' },
  { nomorPengambilan: '20', nama: 'SUNARDI', rt: '02', blok: 'Barat I' },
  { nomorPengambilan: '21', nama: 'RIMA DWI YULIANTO', rt: '02', blok: 'Barat I' },
  { nomorPengambilan: '22', nama: 'ASIH SUDARYANTO', rt: '02', blok: 'Barat I' },
  { nomorPengambilan: '23', nama: 'NETY', rt: '02', blok: 'Barat I' },
  { nomorPengambilan: '24', nama: 'HARYANTO', rt: '02', blok: 'Barat I' },
  { nomorPengambilan: '25', nama: 'MULYANTO T', rt: '02', blok: 'Barat I' },
  { nomorPengambilan: '26', nama: 'MULYANTO T 2', rt: '02', blok: 'Barat I' },
  { nomorPengambilan: '27', nama: 'SULARTO', rt: '02', blok: 'Barat I' },
  { nomorPengambilan: '28', nama: 'MUKIMAN', rt: '02', blok: 'Barat I' },
  { nomorPengambilan: '29', nama: 'SANTI GITO', rt: '02', blok: 'Barat I' },
  { nomorPengambilan: '30', nama: 'NOEK ENDANG PRIHATINI', rt: '02', blok: 'Barat I' },
  { nomorPengambilan: '31', nama: 'H. SUDARNO', rt: '02', blok: 'Barat I' },
  { nomorPengambilan: '32', nama: 'LOWONG', rt: '02', blok: 'Barat I' },
  { nomorPengambilan: '33', nama: 'RUSTIYANTI', rt: '02', blok: 'Barat I' },
  { nomorPengambilan: '34', nama: 'SUNARNO', rt: '02', blok: 'Barat I' },
  { nomorPengambilan: '35', nama: 'KONTRAK PAK PRIYONO', rt: '02', blok: 'Barat I' },
  { nomorPengambilan: '36', nama: 'NIKO', rt: '02', blok: 'Barat I' },
  { nomorPengambilan: '37', nama: 'KONTRAK PAK PRIYONO', rt: '02', blok: 'Barat I' },
  { nomorPengambilan: '38', nama: 'SAPI PAK DARNA', rt: '02', blok: 'BARAT II' },
  { nomorPengambilan: '39', nama: 'PAK TEDI POLSEK', rt: '02', blok: 'BARAT II' },
  { nomorPengambilan: '40', nama: 'YULIADI', rt: '02', blok: 'BARAT II' },
  { nomorPengambilan: '41', nama: 'YUNI (UTARA MASJID)', rt: '02', blok: 'Barat II' },
  { nomorPengambilan: '42', nama: 'EKO NUR H', rt: '02', blok: 'Barat II' },
  { nomorPengambilan: '43', nama: 'ANDRI SETYAWAN', rt: '02', blok: 'Barat II' },
  { nomorPengambilan: '44', nama: 'SUGINO (MADURA)', rt: '02', blok: 'Barat II' },
  { nomorPengambilan: '45', nama: 'H. SYAMSURI', rt: '02', blok: 'Barat II' },
  { nomorPengambilan: '46', nama: 'SRI MARIYANI (SRIYATNO)', rt: '02', blok: 'Barat II' },
  { nomorPengambilan: '47', nama: 'SUGITNA', rt: '02', blok: 'Barat II' },
  { nomorPengambilan: '48', nama: 'SARJIANTO', rt: '02', blok: 'Barat II' },
  { nomorPengambilan: '49', nama: 'SURONO', rt: '02', blok: 'Barat II' },
  { nomorPengambilan: '50', nama: 'YULIADI', rt: '02', blok: 'Barat II' },
  { nomorPengambilan: '51', nama: 'YULIANTO', rt: '02', blok: 'Barat II' },
  { nomorPengambilan: '52', nama: 'SUBANDI', rt: '02', blok: 'Barat II' },
  { nomorPengambilan: '53', nama: 'SURANTO', rt: '02', blok: 'Barat II' },
  { nomorPengambilan: '54', nama: 'TRIYATNO', rt: '02', blok: 'Barat II' },
  { nomorPengambilan: '55', nama: 'ADI UTOMO', rt: '02', blok: 'Barat II' },
  { nomorPengambilan: '56', nama: 'SAMIJAN', rt: '02', blok: 'Barat II' },
  { nomorPengambilan: '57', nama: 'APRILIA', rt: '02', blok: 'Barat II' },
  { nomorPengambilan: '58', nama: 'MUNIR', rt: '02', blok: 'Barat II' },
  { nomorPengambilan: '59', nama: 'LUSIA', rt: '02', blok: 'Barat II' },
  { nomorPengambilan: '60', nama: 'SRIGONO', rt: '02', blok: 'Barat II' },
  { nomorPengambilan: '61', nama: 'AGUNG (KAMPOENG STEAK)', rt: '02', blok: 'Barat II' },
  { nomorPengambilan: '62', nama: 'ANDRI PERUMAHAN', rt: '02', blok: 'Barat II' },
  { nomorPengambilan: '63', nama: 'ABDUL AZIZ MUSLIM', rt: '02', blok: 'Barat II' },
  { nomorPengambilan: '64', nama: 'PETUGAS SAMPAH 1', rt: '02', blok: 'Barat II' },
  { nomorPengambilan: '65', nama: 'PETUGAS SAMPAH 2', rt: '02', blok: 'Barat II' },
  { nomorPengambilan: '66', nama: 'PETUGAS SAMPAH 3', rt: '02', blok: 'Barat II' },
  { nomorPengambilan: '67', nama: 'SYAMSURI (TANAH)', rt: '02', blok: 'Barat II' },
  { nomorPengambilan: '68', nama: 'SUNARNO (TEMPAT)', rt: '02', blok: 'Barat II' },
  { nomorPengambilan: '69', nama: 'KETUA PANITIA (DIAN)', rt: '02', blok: 'Barat II' },
  { nomorPengambilan: '70', nama: 'KARANG TARUNA', rt: '02', blok: 'Barat II' },
  { nomorPengambilan: '71', nama: 'REMAJA MASJID', rt: '02', blok: 'Barat II' },
  { nomorPengambilan: '72', nama: 'TUKIMAN', rt: '02', blok: 'Barat II' },
  { nomorPengambilan: '73', nama: 'LURAH KALIANCAR', rt: '02', blok: 'Barat II' },
  { nomorPengambilan: '74', nama: 'YUKI PERUMAHAN GROBAK', rt: '02', blok: 'Barat II' },
  { nomorPengambilan: '75', nama: 'ENDAH (Perumahan Utara)', rt: '02', blok: 'Barat II' },
  { nomorPengambilan: '76', nama: 'RAHMAT SETIAWAN (Sebelah Bp. Samijan)', rt: '02', blok: 'Barat II' },
  { nomorPengambilan: '77', nama: 'SUYATMIN / SARMI', rt: '02', blok: 'Tengah' },
  { nomorPengambilan: '78', nama: 'Pak RT (TUKIMO)', rt: '02', blok: 'Tengah' },
  { nomorPengambilan: '79', nama: 'SATINO', rt: '02', blok: 'Tengah' },
  { nomorPengambilan: '80', nama: 'YUHENDRIK', rt: '02', blok: 'Tengah' },
  { nomorPengambilan: '81', nama: 'SAKIMO', rt: '02', blok: 'Tengah' },
  { nomorPengambilan: '82', nama: 'DWI NOVI', rt: '02', blok: 'Tengah' },
  { nomorPengambilan: '83', nama: 'NITA (SURONO SKB)', rt: '02', blok: 'Tengah' },
  { nomorPengambilan: '84', nama: 'SUKIMAN', rt: '02', blok: 'Tengah' },
  { nomorPengambilan: '85', nama: 'SUGIYANTO (IKSAN)', rt: '02', blok: 'Tengah' },
  { nomorPengambilan: '86', nama: 'SAIMIN', rt: '02', blok: 'Tengah' },
  { nomorPengambilan: '87', nama: 'AYU MARDIANA', rt: '02', blok: 'Tengah' },
  { nomorPengambilan: '88', nama: 'TUKIMO', rt: '02', blok: 'Tengah' },
  { nomorPengambilan: '89', nama: 'PARNO T', rt: '02', blok: 'Tengah' },
  { nomorPengambilan: '90', nama: 'TUKINO BAMBANG', rt: '02', blok: 'Tengah' },
  { nomorPengambilan: '91', nama: 'DWI SAYOKO', rt: '02', blok: 'Tengah' },
  { nomorPengambilan: '92', nama: 'ANIK REHAN', rt: '02', blok: 'Tengah' },
  { nomorPengambilan: '93', nama: 'DWI YANI M (ALM. TUKIMIN)', rt: '02', blok: 'Tengah' },
  { nomorPengambilan: '94', nama: 'SUGENG', rt: '02', blok: 'Tengah' },
  { nomorPengambilan: '95', nama: 'JAIMIN', rt: '02', blok: 'Tengah' },
  { nomorPengambilan: '96', nama: 'SARNO', rt: '02', blok: 'Tengah' },
  { nomorPengambilan: '97', nama: 'SULARNO', rt: '02', blok: 'Tengah' },
  { nomorPengambilan: '98', nama: 'SUWARTO', rt: '02', blok: 'Tengah' },
  { nomorPengambilan: '99', nama: 'HAYUK', rt: '02', blok: 'Tengah' },
  { nomorPengambilan: '100', nama: 'SRIYONO PATI', rt: '02', blok: 'Tengah' },
  { nomorPengambilan: '101', nama: 'CEPRI M', rt: '02', blok: 'Tengah' },
  { nomorPengambilan: '102', nama: 'FX. SUWARDI', rt: '02', blok: 'Tengah' },
  { nomorPengambilan: '103', nama: 'LIES PURWANTI', rt: '02', blok: 'Tengah' },
  { nomorPengambilan: '104', nama: 'H. ANTOK SRIHONO', rt: '02', blok: 'Tengah' },
  { nomorPengambilan: '105', nama: 'GIMIN', rt: '02', blok: 'Tengah' },
  { nomorPengambilan: '106', nama: 'MARNO', rt: '02', blok: 'Tengah' },
  { nomorPengambilan: '107', nama: 'KAMTO', rt: '02', blok: 'Tengah' },
  { nomorPengambilan: '108', nama: 'JINEM', rt: '02', blok: 'Tengah' },
  { nomorPengambilan: '109', nama: 'SEMIYATI', rt: '02', blok: 'Tengah' },
  { nomorPengambilan: '110', nama: 'SRIYADI (EVI)', rt: '02', blok: 'Tengah' },
  { nomorPengambilan: '111', nama: 'SUGINO P', rt: '02', blok: 'Tengah' },
  { nomorPengambilan: '112', nama: 'H. SUPARMAN', rt: '02', blok: 'Tengah' },
  { nomorPengambilan: '113', nama: 'TOMI', rt: '02', blok: 'Tengah' },
  { nomorPengambilan: '114', nama: 'COUNTER (TOMI)', rt: '02', blok: 'Tengah' },
  { nomorPengambilan: '115', nama: 'SATE MADURA', rt: '02', blok: 'Tengah' },
  { nomorPengambilan: '116', nama: 'Buah (TOMI)', rt: '02', blok: 'Tengah' },
  { nomorPengambilan: '117', nama: 'AYAM KENTUCKY (TOMI)', rt: '02', blok: 'Tengah' },
  { nomorPengambilan: '118', nama: 'TAHU KUPAT (TOMI)', rt: '02', blok: 'Tengah' },
  { nomorPengambilan: '119', nama: 'IS SURAMTO', rt: '02', blok: 'Tengah' },
  { nomorPengambilan: '120', nama: 'NASTITI (Depan Bp. Lowong)', rt: '02', blok: 'Tengah' },
  { nomorPengambilan: '121', nama: 'DEDI KURNIAWAN', rt: '02', blok: 'Timur' },
  { nomorPengambilan: '122', nama: 'ANDREAS', rt: '02', blok: 'Timur' },
  { nomorPengambilan: '123', nama: 'Hj. SUWARNO MH', rt: '02', blok: 'Timur' },
  { nomorPengambilan: '124', nama: 'SURAMTO', rt: '02', blok: 'Timur' },
  { nomorPengambilan: '125', nama: 'Ny. PUNTARI', rt: '02', blok: 'Timur' },
  { nomorPengambilan: '126', nama: 'SUNARYO', rt: '02', blok: 'Timur' },
  { nomorPengambilan: '127', nama: 'SUWARNO AGRA', rt: '02', blok: 'Timur' },
  { nomorPengambilan: '128', nama: 'JOKO DWI HATMONO', rt: '02', blok: 'Timur' },
  { nomorPengambilan: '129', nama: 'SUNARTO', rt: '02', blok: 'Timur' },
  { nomorPengambilan: '130', nama: 'MBAH SAMI', rt: '02', blok: 'Timur' },
  { nomorPengambilan: '131', nama: 'SAMIDI', rt: '02', blok: 'Timur' },
  { nomorPengambilan: '132', nama: 'CATUR / MANA', rt: '02', blok: 'Timur' },
  { nomorPengambilan: '133', nama: 'AGUS SULISTYO', rt: '02', blok: 'Timur' },
  { nomorPengambilan: '134', nama: 'MULYONO (KERNET)', rt: '02', blok: 'Timur' },
  { nomorPengambilan: '135', nama: 'SARTONO BAGONG', rt: '02', blok: 'Timur' },
  { nomorPengambilan: '136', nama: 'IBU SUTANTI (RIKO)', rt: '02', blok: 'Timur' },
  { nomorPengambilan: '137', nama: 'MARYONO AL', rt: '02', blok: 'Timur' },
  { nomorPengambilan: '138', nama: 'KIRNO', rt: '02', blok: 'Timur' },
  { nomorPengambilan: '139', nama: 'ELING PURWANTO', rt: '02', blok: 'Timur' },
  { nomorPengambilan: '140', nama: 'SUPRIYADI (WOLO)', rt: '02', blok: 'Timur' },
  { nomorPengambilan: '141', nama: 'IBU ENDAH (Alm. MARIYONO)', rt: '02', blok: 'Timur' },
  { nomorPengambilan: '142', nama: 'SUPRIYANTO WAGINEM', rt: '02', blok: 'Timur' },
  { nomorPengambilan: '143', nama: 'MARWANTO', rt: '02', blok: 'Timur' },
  { nomorPengambilan: '144', nama: 'ENDANG HONGGI / SUYATNO', rt: '02', blok: 'Timur' },
  { nomorPengambilan: '145', nama: 'SANTO WIYONO', rt: '02', blok: 'Timur' },
  { nomorPengambilan: '146', nama: 'JOKO MULYO', rt: '02', blok: 'Timur' },
  { nomorPengambilan: '147', nama: 'AGUNG SRI SADONO', rt: '02', blok: 'Timur' },
  { nomorPengambilan: '148', nama: 'SATIMAN', rt: '02', blok: 'Timur' },
  { nomorPengambilan: '149', nama: 'SULARDI GLINDING', rt: '02', blok: 'Timur' },
  { nomorPengambilan: '150', nama: 'WINIH', rt: '02', blok: 'Timur' },
  { nomorPengambilan: '151', nama: 'TUKINO HB', rt: '02', blok: 'Timur' },
  { nomorPengambilan: '152', nama: 'SALON (RUKO)', rt: '02', blok: 'Timur' },
  { nomorPengambilan: '153', nama: 'EKO (CHICKEN)', rt: '02', blok: 'Timur' },
  { nomorPengambilan: '154', nama: 'SUYANTO (CUKUR)', rt: '02', blok: 'Timur' },
  { nomorPengambilan: '155', nama: 'JUMINO (MIE GORENG)', rt: '02', blok: 'Timur' },
];
