import { Calendar, Camera, Flag, MapPin, Users, Wallet } from 'lucide-react';

const uang = (n: number) => `Rp ${n.toLocaleString('id-ID')}`;
const kegiatan = ['Perlombaan anak-anak', 'Perlombaan ibu-ibu', 'Perlombaan bapak-bapak', 'Perlombaan lansia', 'Lomba karaoke', 'Jalan santai', 'Acara malam puncak'];
const panitia = [
  ['Pelindung', 'Bp. Moch. Ruri'], ['Penanggung Jawab', 'Bp. Parjan (RT 01); Bp. Tukimo (RT 02)'], ['Ketua Pelaksana', 'Bp. Fatkurohman Tri Hadi'], ['Wakil Ketua', 'Bp. Unggul Prasetiyo; Bp. Eko Rudhi Astanto'], ['Koordinator Pelaksana', 'Bp. Tarmo; Daffa Abid Ash Shidiqiy; Elsa Rahmaningrum; Yogi Wahid Saputra'], ['Sekretaris', 'Bp. Dian Tri Widianto; Latifa Salfa Fainaya'], ['Bendahara', 'Bp. Sakimo; Yasfi Aaidah; Avifahtur Nur; Cornelia Mahidara P.M'], ['Humas', 'Muhammad Al Fatih; Latifa Salfa Fainaya; Pratama Dian Sholiqhin'], ['Dokumentasi', 'Bp. Rezha Adi N; Ferliano Reza Syaputra; Daffa Abid Ash S'], ['Perlengkapan', 'Mufid Akmal Dzaki; Ilham Prakoso; Alvin Teza Firmansyah; Yufen Air Langga'], ['Konsumsi', 'Zullaykha Bunga Avrillea; Anindya Hawa Ainul Fanfa; Marfelia Cahya; Pandi Aji Firmansyah; Rizky Zulfian; Tegar'], ['Keamanan / K3', 'Tri Cahyo Wijanarko; Mufid Akmal Dzaki; Rizky Zulfian'], ['Sie Acara', 'Koordinator: Bp. Sugeng Murjianto'], ['Sie Lomba', 'Bp. Joko Santoso; Bp. Yustinus Ari Gunawan; Asyam Waly Maftuh Shubhi; Fachri Afnan Aditama; Ferliano Reza Syaputra; Ayu Ariyani; Ayu Ariyana; Anindya Hawa Ainul Fanfa; Asyifa Rahmawati; Fathin Nuha; Meysya Rahma'], ['Sie Jalan Santai', 'Reza Putra Adiguna; Morel Haryusta; Najwa Putri Agustin; Alma Rayya Qanitha; Almira Oqila Putri; Dapri Lamelani']
];

const Agustusan = () => (
  <main>
    <section className="relative overflow-hidden bg-gradient-to-br from-red-900 via-red-700 to-rose-700"><div className="max-w-7xl mx-auto px-4 md:px-8 py-12 md:py-20"><div className="grid lg:grid-cols-2 gap-10 items-center"><div className="text-white"><p className="inline-flex items-center gap-2 rounded-full bg-white/15 px-4 py-2 text-sm font-bold"><Flag className="w-4 h-4" /> LPJ HUT Kemerdekaan RI ke-81</p><h1 className="mt-5 text-4xl md:text-6xl font-extrabold leading-tight">Hasil Rangkaian Kegiatan<br /><span className="text-yellow-300">Agustusan 2026</span></h1><p className="mt-5 text-red-100 text-lg">Karang Taruna “Taruna Bhakti” Lingkungan Klampisan</p><div className="mt-8 grid sm:grid-cols-2 gap-3 text-sm"><div className="flex gap-2 items-center rounded-xl bg-white/10 border border-white/20 px-4 py-3"><Calendar className="w-4 h-4" />04–29 Agustus 2026</div><div className="flex gap-2 items-center rounded-xl bg-white/10 border border-white/20 px-4 py-3"><MapPin className="w-4 h-4" />Lapangan voli Bp. Sriyatno RT 01</div></div></div><img src="/WhatsApp Image 2026-08-25 at 09.24.04.jpeg" alt="Poster malam puncak HUT Kemerdekaan RI ke-81 Klampisan" className="w-full rounded-2xl shadow-2xl" /></div></div></section>

    <section className="max-w-7xl mx-auto px-4 md:px-8 py-14 md:py-20"><div className="max-w-3xl"><p className="text-red-600 font-bold text-sm uppercase tracking-wider">Pendahuluan</p><h2 className="mt-2 text-3xl font-extrabold text-gray-900">Tentang kegiatan</h2><p className="mt-4 text-gray-700 leading-relaxed">Dalam rangka memperingati Hari Ulang Tahun Kemerdekaan Republik Indonesia ke-81 Tahun 2026, Karang Taruna “Taruna Bhakti” Lingkungan Klampisan menyelenggarakan serangkaian kegiatan sebagai bentuk rasa syukur dan penghormatan terhadap jasa para pahlawan.</p><p className="mt-3 text-gray-700 leading-relaxed">Kegiatan bertujuan meningkatkan rasa nasionalisme, mempererat tali silaturahmi, menciptakan semangat kebersamaan dan gotong royong, memberi hiburan positif, serta meningkatkan kreativitas dan sportivitas masyarakat.</p></div><div className="mt-10 grid md:grid-cols-2 gap-6"><div className="rounded-2xl bg-stone-50 border border-stone-200 p-6"><h3 className="font-bold text-xl text-gray-900">Identitas pelaksanaan</h3><dl className="mt-4 space-y-3 text-gray-700"><div><dt className="text-gray-500">Nama</dt><dd className="font-semibold">Peringatan Hari Ulang Tahun Kemerdekaan Republik Indonesia ke-81 Tahun 2026</dd></div><div><dt className="text-gray-500">Tema</dt><dd className="font-semibold text-red-700">Sehat, Semangat, Bahagia Bersama, Merdeka!</dd></div><div><dt className="text-gray-500">Penyelenggara</dt><dd className="font-semibold">Karang Taruna “Taruna Bhakti” Klampisan</dd></div><div><dt className="text-gray-500">Peserta</dt><dd className="font-semibold">Masyarakat Desa Klampisan dari anak-anak, orang dewasa, hingga lansia</dd></div></dl></div><div className="rounded-2xl bg-red-50 border border-red-100 p-6"><h3 className="font-bold text-xl text-gray-900">Rangkaian kegiatan</h3><ul className="mt-4 space-y-2 text-gray-700">{kegiatan.map(x => <li key={x} className="flex gap-2"><span className="text-red-600">•</span>{x}</li>)}</ul><p className="mt-5 text-sm text-gray-600">Seluruh rangkaian berjalan baik, lancar, dan mendapat antusiasme positif dari masyarakat Desa Klampisan.</p></div></div></section>

    <section className="bg-stone-50 border-y border-stone-100 px-4 md:px-8 py-14 md:py-20"><div className="max-w-7xl mx-auto"><div className="flex items-center gap-3"><Wallet className="text-green-700" /><div><p className="text-green-700 font-bold text-sm uppercase tracking-wider">Laporan keuangan</p><h2 className="text-3xl font-extrabold text-gray-900">Rekapitulasi dana kegiatan</h2></div></div><div className="mt-8 grid md:grid-cols-3 gap-5">{[['Total pemasukan', uang(47871500), 'text-green-700'], ['Total pengeluaran', uang(47655710), 'text-red-700'], ['Sisa / saldo akhir', uang(215790), 'text-amber-700']].map(([label, value, color]) => <div key={label} className="bg-white rounded-2xl p-6 shadow-sm border border-gray-100"><p className="text-gray-500">{label}</p><p className={`mt-2 text-2xl font-extrabold ${color}`}>{value}</p></div>)}</div><p className="mt-6 text-gray-700">Sumber dana diperoleh dari masyarakat Klampisan, instansi, dan pelaku usaha. Rincian transaksi tercantum dalam lampiran laporan.</p></div></section>

    <section className="max-w-7xl mx-auto px-4 md:px-8 py-14 md:py-20"><div className="grid lg:grid-cols-2 gap-6"><div className="rounded-2xl border border-gray-200 p-6"><h2 className="text-2xl font-extrabold">Evaluasi kegiatan</h2><div className="mt-5 space-y-4 text-gray-700"><p><strong>Faktor pendukung:</strong> antusiasme masyarakat, kerja sama panitia, dukungan masyarakat dan perangkat desa, dukungan donatur, serta partisipasi peserta yang baik.</p><p><strong>Kendala:</strong> keterbatasan waktu persiapan, beberapa perlengkapan mengalami kendala teknis, koordinasi antarbagian perlu ditingkatkan, dan penyesuaian kondisi lapangan.</p><p><strong>Solusi dan hasil:</strong> panitia melakukan koordinasi langsung serta penyesuaian teknis. Secara keseluruhan kegiatan terlaksana dengan baik, mendapat respons positif, dan meningkatkan kebersamaan serta gotong royong warga.</p></div></div><div className="rounded-2xl border border-gray-200 p-6"><h2 className="text-2xl font-extrabold">Penutup</h2><p className="mt-5 text-gray-700 leading-relaxed">LPJ ini dibuat sebagai bentuk pertanggungjawaban atas pelaksanaan kegiatan. Panitia mengucapkan terima kasih kepada seluruh pihak yang memberikan tenaga, pikiran, materi, maupun doa. Kami menyadari masih terdapat kekurangan dan memohon maaf atas segala kekurangan tersebut.</p><p className="mt-3 text-gray-700 leading-relaxed">Semoga laporan ini menjadi bahan evaluasi dan dokumentasi bagi Karang Taruna “Taruna Bhakti” Lingkungan Klampisan.</p></div></div></section>

    <section className="bg-gray-950 text-white px-4 md:px-8 py-14 md:py-20"><div className="max-w-7xl mx-auto"><div className="flex items-center gap-3"><Users className="text-red-400" /><div><p className="text-red-400 font-bold text-sm uppercase tracking-wider">Lampiran laporan</p><h2 className="text-3xl font-extrabold">Susunan panitia</h2></div></div><div className="mt-8 grid md:grid-cols-2 lg:grid-cols-3 gap-4">{panitia.map(([jabatan, anggota]) => <div key={jabatan} className="rounded-xl bg-white/5 border border-white/10 p-4"><h3 className="font-bold text-red-300">{jabatan}</h3><p className="mt-2 text-sm text-gray-300 leading-relaxed">{anggota}</p></div>)}</div></div></section>

    <section className="max-w-7xl mx-auto px-4 md:px-8 py-14 md:py-20"><div className="flex items-center gap-3 mb-6"><Camera className="text-red-600" /><div><p className="text-red-600 font-bold text-sm uppercase tracking-wider">Dokumentasi</p><h2 className="text-3xl font-extrabold text-gray-900">Momen kegiatan Klampisan</h2></div></div><div className="max-w-4xl"><img src="/WhatsApp Image 2026-08-24 at 18.02.50.jpeg" alt="Dokumentasi kegiatan warga Klampisan" className="w-full aspect-[4/3] object-cover rounded-2xl shadow-md" /></div></section>
  </main>
);
export default Agustusan;
